server:
  port: 8099

#spring:
#  h2:
#    console:
#      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
#      path: /test  # 콘솔의 경로

#  datasource:
#    driver-class-name: org.h2.Driver  #h2 드라이버 설정
#    url: jdbc:h2:~/test  #접속 URL
#    username: sa